C_FLAGS=-g -Wall -march=native
C_INCLUDES=-Iinclude -I3rd/3dm/include -I3rd/ffmpeg/include -I3rd/glfw-3.2.1/include -I/System/Library/Frameworks/OpenGL.framework/Headers
LDLIBS=-L3rd/ffmpeg/lib -L3rd/glfw-3.2.1/lib -lm -framework OpenGL -lglfw3 -lpthread -lavformat -lavcodec -lavutil -lswscale -lswresample -lz -lstdc++  -lx264 -lx265 -lopenh264 -lvpx -ltwolame -lmp3lame -lopus  -lavcodec -framework QuartzCore -framework QuartzCore -framework AppKit -framework OpenGL -framework QuartzCore -framework AppKit -framework OpenGL -framework CoreVideo -framework Foundation -framework AVFoundation -framework CoreMedia -framework CoreFoundation -framework VideoToolbox -framework CoreMedia -framework CoreVideo -framework CoreFoundation -framework AudioToolbox -framework CoreMedia -framework VideoDecodeAcceleration -framework CoreFoundation -framework QuartzCore -L/opt/local/lib -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-shm -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-shape -lxcb -lXau -lXdmcp -Wl,-framework,CoreFoundation -Wl,-framework,Security -L/opt/local/lib -lSDL2 -lm -liconv -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -framework QuartzCore -framework QuartzCore -framework AppKit -framework OpenGL -framework QuartzCore -framework AppKit -framework OpenGL -framework CoreVideo -framework Foundation -framework AVFoundation -framework CoreMedia -framework CoreFoundation -framework VideoToolbox -framework CoreMedia -framework CoreVideo -framework CoreFoundation -framework AudioToolbox -framework CoreMedia -framework VideoDecodeAcceleration -framework CoreFoundation -framework QuartzCore -L/opt/local/lib -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-shm -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -L/opt/local/lib -lxcb-shape -lxcb -lXau -lXdmcp -Wl,-framework,CoreFoundation -Wl,-framework,Security -L/opt/local/lib -lSDL2 -lm -liconv -Wl,-framework,CoreAudio -Wl,-framework,AudioToolbox -Wl,-framework,ForceFeedback -lobjc -Wl,-framework,CoreVideo -Wl,-framework,Cocoa -Wl,-framework,Carbon -Wl,-framework,IOKit -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/out/build-mac/lib -lx265 -lc++ -ldl -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lx264 -lpthread -lm -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lvpx -lm -lpthread -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lvpx -lm -lpthread -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lvpx -lm -lpthread -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lvpx -lm -lpthread -ltwolame -ltwolame -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lopus -L/Volumes/Unity3DWorks/GoProjects/iONTranscoder2/3rd/ffmpeg/../out/build-mac/lib -lopenh264 -lstdc++ -lmp3lame -framework CoreGraphics -lm -lbz2 -lz -pthread -framework CoreServices
SOURCES=3rd/3dm/src/*.c src/*.c valo.c

clang:
	clang -std=c11 $(C_FLAGS) $(C_INCLUDES) $(LDLIBS) -o valo $(SOURCES)

gcc:
	gcc -std=c99 -Wno-psabi $(C_FLAGS) $(C_INCLUDES) $(LDLIBS) -o valo $(SOURCES)
